; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\objects\delay.s --depend=.\objects\delay.d --cpu=Cortex-M3 --apcs=interwork --diag_suppress=9931 -I.\dustwind\inc -I.\dustwind\sysinc -I.\RTE\Device\STM32F103ZE -I.\RTE\_6000 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\StdPeriph_Driver\inc -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F10X_HD -DSTM32F10X_HD --omf_browse=.\objects\delay.crf dustwind\src\delay.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.Delay||, CODE, READONLY, ALIGN=2

Delay PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        B        |L0.14|
|L0.6|
        ADR      r0,|L0.20|
        SUBS     r4,r4,#1
        BL       asm
|L0.14|
        CMP      r4,#0
        BNE      |L0.6|
        POP      {r4,pc}
        ENDP

|L0.20|
        DCB      "NOP",0

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT Delay [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT asm [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
